-- MySQL Script generated by MySQL Workbench
-- dom 25 oct 2020 13:38:53 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema konecta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema konecta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `konecta` DEFAULT CHARACTER SET utf8 ;
USE `konecta` ;

-- -----------------------------------------------------
-- Table `konecta`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konecta`.`usuario` (
  `usuarioid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(70) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuarioid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konecta`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konecta`.`producto` (
  `productoid` INT NOT NULL AUTO_INCREMENT,
  `usuarioid` INT NOT NULL,
  `nom_producto` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `peso` INT NOT NULL,
  `stock` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`productoid`),
  INDEX `fk_producto_usuario_idx` (`usuarioid` ASC),
  CONSTRAINT `fk_producto_usuario`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `konecta`.`usuario` (`usuarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `konecta`.`historial_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `konecta`.`historial_ventas` (
  `historialid` INT NOT NULL AUTO_INCREMENT,
  `productoid` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`historialid`),
  INDEX `fk_historial_ventas_producto1_idx` (`productoid` ASC),
  CONSTRAINT `fk_historial_ventas_producto1`
    FOREIGN KEY (`productoid`)
    REFERENCES `konecta`.`producto` (`productoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `konecta`;

DELIMITER $$
USE `konecta`$$
CREATE TRIGGER fecha_producto BEFORE INSERT ON producto 
FOR EACH ROW
SET NEW.fecha_creacion = NOW();$$

USE `konecta`$$
CREATE TRIGGER ventas BEFORE INSERT ON historial_ventas 
FOR EACH ROW
SET NEW.fecha_creacion = NOW();$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
